# Setup
title:              "Bootstrap Expo"
description:        "Beautiful and inspiring uses of Bootstrap"
url:                "https://expo.getbootstrap.com"
future:             false
permalink:          pretty
paginate:           10

source:             src

# Settings
destination:        ./_site

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
    style:          compressed

# Local Server
host:               localhost # same as default value '127.0.0.1' but reads better

# Links
#expo_repo:          https://github.com/twbs/bootstrap-expo
expo_new_issue:     https://github.com/twbs/bootstrap-expo/issues/new
docs:               https://getbootstrap.com
blog:               https://blog.getbootstrap.com

redirect_from:
  json: false

# Social
author:
  twitter:      "mdo"

twitter:
  card:         "summary_large_image"
  username:     "getbootstrap"

logo:           "/assets/img/bootstrap-social.png"

# Output
defaults:
  - scope:
      path:     ""
    values:
      image:
        path:   "/assets/img/bootstrap-social.png" # default image
        width:  1200
        height: 630
