name: CI

on: [push, pull_request]

env:
  RUBY: 2.7

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ env.RUBY }}"
          bundler-cache: true

      - name: Version info
        run: |
          ruby --version
          gem --version
          bundle --version

      - run: bundle exec jekyll build
      - run: bundle exec jekyll doctor
